import React from "react";

import "../LearningOptions/LearningOptions.css";

const BPMeasurement = (props) => {
  const options = [
    { text: "What is blood pressure measured in?", handler: () => {props.actionProvider.handleRequest("What is blood pressure measured in?"); props.actionProvider.handleNewMessage("Blood pressure is measured in millimetres of mercury, which is noted as mmHg")}, id: 1 },
    { text: "What is the procedure like?", handler: () => {props.actionProvider.handleRequest("What is the procedure like?"); props.actionProvider.handleNewMessage("The cuff is wrapped around your upper arm and inflated until it feels tight, which limits blood flow to the rest of your arm. It can cause slight discomfort, but the tightness only lasts for a couple of seconds. The cuff is then slowly deflated, which lets blood flow return to normal. The sound of blood pulsing back into the arteries is used to measure blood pressure."); props.actionProvider.handleNewImageMessage("If your doctor is using a manual monitor, they will listen to the sound with a stethoscope. An automatic monitor will inflate the cuff and take the blood pressure readings with just the push of a button.", "bp_procedure")}, id: 2 },
    { text: "What do the blood pressure numbers mean?", handler: () => {props.actionProvider.handleRequest("What do the blood pressure numbers mean?"); props.actionProvider.handleNewVideoMessage("All blood pressure measurements include two numbers which are systolic blood pressure (SBP) and diastolic blood pressure (DBP). These numbers reflect the pressure against blood vessel walls when the heart contracts (SBP) and relaxes (DBP) every time it beats", "https://www.youtube.com/embed/FSjLLPuTkPI")}, id: 3 },
    { text: "Can you give an example of a normal blood pressure measure?", handler: () => { props.actionProvider.handleRequest("Can you give an example of a normal blood pressure measure?"); props.actionProvider.handleNewMessage("A typical blood pressure measurement may look like this: 120/80 mmHg, which is read as “120 over 80 millimetres of mercury”. The first number (120) is the SBP, and the second number (80) is the DBP")}, id: 4 },
    { text: "Office BP", handler: () => {props.actionProvider.handleRequest("Office BP"); props.actionProvider.handleNewMessage("Blood pressure measured in a clinical setting, like the hospital or your GP's office, is known as an office blood pressure measurement (OBPM). The steps for the procedure are shown below:"); props.actionProvider.handleNewMessage("1. Patients should be seated comfortably in a quiet environment for 5 min before beginning BP measurements"); props.actionProvider.handleNewMessage("2. Three BP measurements should be recorded, 1-2 min apart, and additional measurements only if the first two readings differ by >10 mmHg. BP is recorded as the average of the last two BP readings.");props.actionProvider.handleNewMessage("3. Additional measurements may have to be performed in patients with unstable BP values due to arrhythmias, such as in patents with AF, in whom manual auscultatory methods should be used as most automated devices have not been validated for BP measurement in patients with AF."); props.actionProvider.handleNewMessage("4. Use a standard bladder cuff (12–13 cm wide and 35 cm long) for most patients, but have larger and smaller cuffs available for larger (arm circumference >32 cm) and thinner arms, respectively."); props.actionProvider.handleNewMessage("5. The cuff should be positioned at the level of the heart, with the back and arm supported to avoid muscle contraction and isometric exercise-dependant increases in BP."); props.actionProvider.handleNewMessage("6. When using auscultatory methods, use phase I and V (sudden reduction/disappearance) Korotkoff sounds to identify SBP and DBP, respectively."); props.actionProvider.handleNewMessage("7. Measure BP in both arms at the first visit to detect possible between-arm differences. Use the arm with the higher value as the reference."); props.actionProvider.handleNewMessage("8. Measure BP 1 min and 3 min after standing from a seated position in all patients at the first measurement to exclude orthostatic hypotension. Lying and standing BP measurements should also be considered in subsequent visits in older people, people with diabetes, and people with other conditions in which orthostatic hypotension may frequently occur."); props.actionProvider.handleNewMessage("9. Record heart rate and use pulse palpation to exclude arrhythmia."); props.actionProvider.handleNewImageMessage("An example of how this looks is shown below:", "office_bp")}, id: 5 },
    { text: "Home BP Measurement", handler: () => {props.actionProvider.handleRequest("Home BP Measurement"); props.actionProvider.handleNewImageMessage("This is a method of measuring your blood pressure at home using a blood pressure monitor. It is able to give us better accurate readings compared to when it is checked at the clinic or at your GP.", "bp_advice"); props.actionProvider.handleNewVideoMessage("Here is a brief video explaining this in more detail", "https://www.youtube.com/embed/iEwqy3lzK0c")}, id: 6 },
    { text: "Ambulatory BP Measurement", handler: () => {props.actionProvider.handleRequest("Ambulatory BP Measurement"); props.actionProvider.handleNewMessage("This is a method of measuring your blood pressure is monitored for 24 hrs using a portable device. A small digital blood pressure monitor is attached to a belt around your waist and connected to a cuff around your upper arm")}, id: 7 },
  ];

  const optionsMarkup = options.map((option) => (
    <button
      className="learning-option-button"
      key={option.id}
      onClick={option.handler}
    >
      {option.text}
    </button>
  ));

  return <div className="learning-options-container">{optionsMarkup}</div>;
};

export default BPMeasurement;
